#generate_less_data: generate_less_data.c file0.h file0.cc
#	gcc -o generate_less_data -pedantic -std=gnu99 -Wall generate_less_data.c file0.h file0.cc -lm

read_test: read_test.c file0.h file0.cc
	gcc -o read_test -pedantic -std=gnu99 -Wall read_test.c file0.h file0.cc -lm

